export default {
   UPDATE_CURRENT_SEASON: 'UPDATE_CURRENT_SEASON',
   UPDATE_CURRENT_EPISODE: 'UPDATE_CURRENT_EPISODE',
   START_ADD_MOVIE: 'START_ADD_MOVIE',
   ADD_MOVIE: 'ADD_MOVIE',
   RESET_ITEM: 'RESET_ITEM'
}