export const UPDATE_CURRENT_SEASON = 'UPDATE_CURRENT_SEASON';
export const UPDATE_CURRENT_EPISODE = 'UPDATE_CURRENT_EPISODE';
export const ADD_MOVIE_STARTED = 'ADD_MOVIE_STARTED';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
